# Generated by Django 4.1.6 on 2023-02-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='clientName',
            field=models.CharField(max_length=50, verbose_name='نام مشتری'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='dealer',
            field=models.CharField(max_length=50, verbose_name='نام کارشناس'),
        ),
    ]
