# Generated by Django 4.1.6 on 2023-02-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_contract_clientname_alter_contract_dealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='clientNumber',
            field=models.CharField(max_length=11, unique=True, verbose_name='شماره مشتری'),
        ),
    ]
