# Generated by Django 4.1.6 on 2023-02-19 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_contract_clientnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
