# Generated by Django 4.1.6 on 2023-02-21 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0004_contract_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='منتشرکننده'),
            preserve_default=False,
        ),
    ]
